Feature Manage Cities - Fourth Challenge
FranRossi/FourthChallenge-LightIt pull request #1
Opened 2023-04-05 14:12 UTC by FranRossi

TL;DR
Completes the entire section of Managing a City for the fourth Challenge.

Main section of cities with the correspondent table and pagination of 5 cities per page.

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/65981860/230097416-8691eb90-40a6-46d3-8665-6a63c01632aa.png">

I used tailwind components to make everything more consistent, and Ajax with Jquery for the CRUD actions. 
For the views, I use blade components. I do have a "home" component called layout which enables to reuse the styling for future pages.

For the Update action, I used a separate form that has all the information that can be changed except the id.

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/65981860/230105091-227da91c-b488-4d46-b78e-6e06d1bc4618.png">

The error handling it is not finished. I just show an alert message when an error happens, in the future I will change it to show flash messages.
For example when trying to edit the city London and change the name of the city , which must be unique, to one that already exist it shows this alert message.

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/65981860/230106965-980cc5a4-6ffd-4596-83f6-7387e8bcf990.png">

Probably making shorter Pull Request in the future.

2023-04-05 14:33 UTC, felipe-crosa commented on fourth-challenge/app/Http/Controllers/CityController.php
> +        $city = $city ?: new City();
No esta mal, solo como comentario:
En php existe el operador ?? que su funcion es justamente evitar este tipo de terniary expressions. Lo que hace ese operador es si vos pones valor1 ?? valor2, si el valor 1 es null entonces te retorna el valor2, sino devuelve el valor1. Justo en este caso te vendria util ya que podrias hacer $city = $city ?? new City()

2023-04-05 14:37 UTC, felipe-crosa-7S commented on fourth-challenge/app/Http/Controllers/CityController.php
> +        $direction = $request->input('direction');
Podrias validar el contenido de estos campos porque sino creo que si llegas a hacer un orderBy de una columna que no existe se te va a caer

2023-04-05 14:37 UTC, felipe-crosa commented on fourth-challenge/app/Http/Controllers/CityController.php
> +        $direction = $request->input('direction');
Podrias validar el contenido de estos campos porque sino creo que si llegas a hacer un orderBy de una columna que no existe se te va a caer

2023-04-05 14:41 UTC, FranRossi commented on fourth-challenge/app/Http/Controllers/CityController.php
> +        $city = $city ?: new City();
Gracias por el comentario! Voy a cambiarlo como me sugeriste para usar ese operador de php

2023-04-05 14:45 UTC, felipe-crosa commented on fourth-challenge/tests/Feature/Cities/CityTest.php
> +            ->assertSessionHasErrors('flights_departing');
Para este tipo de tests que lo que haces en fin es repetir la misma assertion con pequeños cambios en los body de los requests, phpunit tiene lo que son dataProviders (https://phpunit.de/manual/3.7/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers). Esta funcionalidad te permite escribir un solo test y despues especificar una lista de distintos escenarios con los que queres que se corra, te sirve para evitar duplicar codigo, te queda mas prolijo y en fin dejas solo una assertion por test que es mejor practica

2023-04-05 14:48 UTC, felipe-crosa commented on fourth-challenge/app/Http/Controllers/CityController.php
> +            'flights_departing' => ['required', 'integer']
que pasa si te tira un negativo?

2023-04-05 17:33 UTC, Juan2418 requested changes
Summing up, I know you already know this but, this PR is huge

2023-04-05 17:33 UTC, Juan2418 commented on fourth-challenge/app/Http/Controllers/CityController.php
> +//            'flights_arriving' => ['required', 'integer', 'min:0', ],
These comments should be deleted

2023-04-05 17:33 UTC, Juan2418 commented on fourth-challenge/public/js/cities/form.js
> +            error: function(xhr, status, error) {
As a general rule, I would not create any pr with todos if I can help it. Either resolve all the todos before the request or those you won't resolve now can be loaded to the management system of choice

2023-04-05 17:33 UTC, Juan2418 commented on fourth-challenge/public/js/cities/form.js
> +                // Reset the form inputs
Is this comment necessary? If the code is not clear enough that you need to mark the code section with a subtitle maybe consider extracting the block into an auxiliary function

2023-04-05 17:33 UTC, Juan2418 commented on fourth-challenge/public/js/cities/form.js
> +        var formData = $(this).serialize();
Why `var`?

2023-04-05 17:33 UTC, Juan2418 commented on fourth-challenge/public/js/cities/table.js
> +        e.preventDefault();
Same thing with the comments

2023-04-05 17:33 UTC, Juan2418 commented on fourth-challenge/resources/views/cities/edit-form.blade.php
> +{{--            TODO pasarlo a un componente--}}
Same thing here with the TODOs and please choose a language and stick with it, either everything in Spanish or everything in English. One or the other in this context is the same to me but consistency is important

2023-04-05 17:33 UTC, Juan2418 commented on fourth-challenge/resources/views/components/layout.blade.php
> +{{--                <div class="hidden md:block">--}}
What is this huge comment about? Should it be there?

2023-04-05 17:33 UTC, Juan2418 commented on fourth-challenge/resources/views/components/table-header-sort.blade.php
> +        <!-- Active: "bg-gray-200 text-gray-900 group-hover:bg-gray-300", Not Active: "invisible text-gray-400 group-hover:visible group-focus:visible" -->
Is this comment necessary?

2023-04-05 17:33 UTC, Juan2418 commented on fourth-challenge/routes/web.php
> +//Route::get('/', [CityController::class, 'index']);
Shouldn't this be deleted?

2023-04-05 17:54 UTC, FranRossi commented
> Summing up, I know you already know this but, this PR is huge

Thanks for all the comments! Yes I know it is huge, my bad won't happen again

2023-04-05 19:17 UTC, Juan2418 requested changes

2023-04-05 19:17 UTC, Juan2418 commented on fourth-challenge/public/js/cities/table.js
> +        console.log("Sorting by column: " + column + " in direction: " + direction);
Unless this log is a requirement, please avoid unnecessary logs on the client

2023-04-06 12:52 UTC, FranRossi commented on fourth-challenge/app/Http/Controllers/CityController.php
> +        $direction = $request->input('direction');
Si, tenés razón. Voy a agregar una validación sobre estos campos

2023-04-06 12:52 UTC, FranRossi commented on fourth-challenge/app/Http/Controllers/CityController.php
> +            'flights_departing' => ['required', 'integer']
Bien, no lo había visto a eso, ya quedo solucionado

2023-04-06 12:52 UTC, FranRossi commented on fourth-challenge/tests/Feature/Cities/CityTest.php
> +            ->assertSessionHasErrors('flights_departing');
Si, perfecto. Ya lo cambie y queda mucho mas prolijo

2023-04-06 12:52 UTC, FranRossi commented on fourth-challenge/app/Http/Controllers/CityController.php
> +//            'flights_arriving' => ['required', 'integer', 'min:0', ],
Right I was just trying to use accessors for this fields that Felipe suggested me earlier, and I forgot to delete these comments

2023-04-06 12:53 UTC, merged